# FilterCatStringSelect { #shiny_adaptive_filter.FilterCatStringSelect }

```python
FilterCatStringSelect(self, *, label=None)
```



## Methods

| Name | Description |
| --- | --- |
| [matching_rows](#shiny_adaptive_filter.FilterCatStringSelect.matching_rows) | Calculates the rows that match the current filter |
| [narrow_options](#shiny_adaptive_filter.FilterCatStringSelect.narrow_options) | Updates the current filter values based on the values from other filters. |

### matching_rows { #shiny_adaptive_filter.FilterCatStringSelect.matching_rows }

```python
FilterCatStringSelect.matching_rows()
```

Calculates the rows that match the current filter
and returns an Index of the .matching rows

### narrow_options { #shiny_adaptive_filter.FilterCatStringSelect.narrow_options }

```python
FilterCatStringSelect.narrow_options(valid_rows)
```

Updates the current filter values based on the values from other filters.
This only does the component update,
it does not perform the calculations needed to figure out what